In [50]:
import pandas as pd
import numpy as np
import sklearn

In [51]:
df = pd.read_csv('data-use.csv')
df

,Tên xe,Giá,Năm sản xuất,Kiểu dáng,Tình trạng,Xuất xứ,Số km đã đi,Tỉnh thành,Hộp số,Nhiên liệu
0,Mercedes-Benz CLA 250 4Matic 2014,8.450000e+08,2014,Sedan,Đãquasửdụng,Trongnước,78.858km,HàNội,Sốtựđộng,NaN
1,Mercedes-Benz C 250 Exclusive 2016,1.119000e+09,2016,Sedan,Đãquasửdụng,Trongnước,51.499km,Tp.HCM,Sốtựđộng,Xăng
2,Mercedes-Benz GLC 200 4Matic 2021,1.789000e+09,2021,SUV,Đãquasửdụng,Nhậpkhẩu,8.000km,Tp.HCM,Sốtựđộng,Xăng
3,Mitsubishi Xpander 1.5MT 2021,5.200000e+08,2021,MPV,Đãquasửdụng,Nhậpkhẩu,10.000km,HàNội,Sốtay,Xăng
4,Kia Forte S 2.0 AT 2009,3.200000e+08,2009,Sedan,Đãquasửdụng,Trongnước,90.000km,HàNội,Sốtựđộng,Xăng
...,...,...,...,...,...,...,...,...,...,...
3255,Toyota Camry 2.5Q 2018,8.980000e+08,2018,Sedan,Đãquasửdụng,Trongnước,50.000km,HàNội,Sốtựđộng,Xăng
3256,Toyota Yaris 1.3G 2014,3.800000e+08,2014,Hatchback,Đãquasửdụng,Nhậpkhẩu,92.000km,Tp.HCM,Sốtựđộng,Xăng
3257,Toyota Camry 1993,1.270000e+08,1993,Sedan,Đãquasửdụng,Nhậpkhẩu,68.000km,Tp.HCM,Sốtựđộng,Xăng
3258,Ford Everest 2.5AT 2016,5.650000e+08,2016,SUV,Đãquasửdụng,Nhậpkhẩu,6.000km,Tp.HCM,Sốtựđộng,Diesel
3259,BMW 328i GT 2014,8.990000e+08,2014,Sedan,Đãquasửdụng,Nhậpkhẩu,82.000km,HàNội,NaN,NaN

In [52]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3260 entries, 0 to 3259
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tên xe        3260 non-null   object
 1   Giá           3139 non-null   float64
 2   Năm sản xuất  3246 non-null   object
 3   Kiểu dáng     3139 non-null   object
 4   Tình trạng    3139 non-null   object
 5   Xuất xứ       3139 non-null   object
 6   Số km đã đi   3113 non-null   object
 7   Tỉnh thành    3012 non-null   object
 8   Hộp số        2895 non-null   object
 9   Nhiên liệu    2296 non-null   object
dtypes: float64(1), object(9)
memory usage: 254.8+ KB
None

In [53]:
# Xóa "km" từ cột 'Số km đã đi'
df['Số km đã đi'] = df['Số km đã đi'].str.replace('km', '')
df

,Tên xe,Giá,Năm sản xuất,Kiểu dáng,Tình trạng,Xuất xứ,Số km đã đi,Tỉnh thành,Hộp số,Nhiên liệu
0,Mercedes-Benz CLA 250 4Matic 2014,8.450000e+08,2014,Sedan,Đãquasửdụng,Trongnước,78.858,HàNội,Sốtựđộng,NaN
1,Mercedes-Benz C 250 Exclusive 2016,1.119000e+09,2016,Sedan,Đãquasửdụng,Trongnước,51.499,Tp.HCM,Sốtựđộng,Xăng
2,Mercedes-Benz GLC 200 4Matic 2021,1.789000e+09,2021,SUV,Đãquasửdụng,Nhậpkhẩu,8.000,Tp.HCM,Sốtựđộng,Xăng
3,Mitsubishi Xpander 1.5MT 2021,5.200000e+08,2021,MPV,Đãquasửdụng,Nhậpkhẩu,10.000,HàNội,Sốtay,Xăng
4,Kia Forte S 2.0 AT 2009,3.200000e+08,2009,Sedan,Đãquasửdụng,Trongnước,90.000,HàNội,Sốtựđộng,Xăng
...,...,...,...,...,...,...,...,...,...,...
3255,Toyota Camry 2.5Q 2018,8.980000e+08,2018,Sedan,Đãquasửdụng,Trongnước,50.000,HàNội,Sốtựđộng,Xăng
3256,Toyota Yaris 1.3G 2014,3.800000e+08,2014,Hatchback,Đãquasửdụng,Nhậpkhẩu,92.000,Tp.HCM,Sốtựđộng,Xăng
3257,Toyota Camry 1993,1.270000e+08,1993,Sedan,Đãquasửdụng,Nhậpkhẩu,68.000,Tp.HCM,Sốtựđộng,Xăng
3258,Ford Everest 2.5AT 2016,5.650000e+08,2016,SUV,Đãquasửdụng,Nhậpkhẩu,6.000,Tp.HCM,Sốtựđộng,Diesel
3259,BMW 328i GT 2014,8.990000e+08,2014,Sedan,Đãquasửdụng,Nhậpkhẩu,82.000,HàNội,NaN,NaN

In [54]:
# Check for missing values
print(df.isnull().sum())

Tên xe            0
Giá             121
Năm sản xuất     14
Kiểu dáng       121
Tình trạng      121
Xuất xứ         121
Số km đã đi     147
Tỉnh thành      248
Hộp số          365
Nhiên liệu      964
dtype: int64

In [55]:
# Check for duplicate rows
print(df.duplicated().sum())

1754

In [56]:
# Remove duplicates
df = df.drop_duplicates(subset=["Tên xe", "Năm sản xuất"])

In [57]:
print(df.duplicated().sum())

0

In [58]:
# Loại bỏ các bản ghi có giá trị "Số km đã đi" bằng giá trị cụ thể
df = df[df["Số km đã đi"] != "HàNội"]
df = df[df["Số km đã đi"] != "Tp.HCM"]
df = df[df["Số km đã đi"] != "BìnhDương"]
df = df[df["Số km đã đi"] != "HảiPhòng"]
df = df[df["Số km đã đi"] != "BìnhPhước"]
df = df[df["Số km đã đi"] != "NinhBình"]
df = df[df["Số km đã đi"] != "BàRịaVũngTàu"]
df = df[df["Số km đã đi"] != "VĩnhPhúc"]
df = df[df["Số km đã đi"] != "ĐàNẵng"]

In [59]:
# Chỉ xóa các giá trị NaN trong cột "Tên cột"
df.dropna(subset=["Số km đã đi"], inplace=True)
# Loại bỏ dấu chấm phân tách phần ngàn từ chuỗi
df["Số km đã đi"] = df["Số km đã đi"].str.replace('.', '')

# Chuyển đổi kiểu dữ liệu từ chuỗi sang số nguyên
df["Số km đã đi"] = df["Số km đã đi"].astype(int)
df["Năm sản xuất"] = df["Năm sản xuất"].astype(int)

In [60]:
# Impute missing values in numerical columns
df["Giá"] = df["Giá"].fillna(df["Giá"].mean())
df["Số km đã đi"] = df["Số km đã đi"].fillna(df["Số km đã đi"].median())

In [61]:
# Kiểm tra giá trị rỗng sau khi xử lý
missing_gia = df["Giá"].isnull().sum()
print("Số lượng giá trị rỗng trong cột 'Tên cột':", missing_gia)

missing_km = df["Số km đã đi"].isnull().sum()
print("Số lượng giá trị rỗng trong cột 'Tên cột':", missing_km)

Số lượng giá trị rỗng trong cột 'Tên cột': 0
Số lượng giá trị rỗng trong cột 'Tên cột': 0

In [64]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1074 entries, 0 to 1789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tên xe        1074 non-null   object
 1   Giá           1074 non-null   float64
 2   Năm sản xuất  1074 non-null   int32
 3   Kiểu dáng     1074 non-null   object
 4   Tình trạng    1074 non-null   object
 5   Xuất xứ       1074 non-null   object
 6   Số km đã đi   1074 non-null   int32
 7   Tỉnh thành    985 non-null    object
 8   Hộp số        984 non-null    object
 9   Nhiên liệu    920 non-null    object
dtypes: float64(1), int32(2), object(7)
memory usage: 83.9+ KB
None

In [73]:
# Kiểm tra số lượng bản ghi trống hoặc NaN của cột "hộp số"
missing_values = df["Hộp số"].isnull().sum()
print("Số lượng bản ghi trống hoặc NaN của cột 'hộp số':", missing_values)

Số lượng bản ghi trống hoặc NaN của cột 'hộp số': 0

In [74]:
unique_values = df['Nhiên liệu'].unique()
print(unique_values)

['Xăng' 'Diesel' 'Loạikhác']

In [75]:
df.dropna(inplace=True)

# Hiển thị DataFrame sau khi loại bỏ NaN từ cột 'ten_cot'
df

,Tên xe,Giá,Năm sản xuất,Kiểu dáng,Tình trạng,Xuất xứ,Số km đã đi,Tỉnh thành,Hộp số,Nhiên liệu
1,Mercedes-Benz C 250 Exclusive 2016,1.119000e+09,2016,Sedan,Đãquasửdụng,Trongnước,51499,Tp.HCM,Sốtựđộng,Xăng
2,Mercedes-Benz GLC 200 4Matic 2021,1.789000e+09,2021,SUV,Đãquasửdụng,Nhậpkhẩu,8000,Tp.HCM,Sốtựđộng,Xăng
3,Mitsubishi Xpander 1.5MT 2021,5.200000e+08,2021,MPV,Đãquasửdụng,Nhậpkhẩu,10000,HàNội,Sốtay,Xăng
4,Kia Forte S 2.0 AT 2009,3.200000e+08,2009,Sedan,Đãquasửdụng,Trongnước,90000,HàNội,Sốtựđộng,Xăng
5,Hyundai Tucson 2.0 Đặc biệt 2016,7.300000e+08,2016,SUV,Đãquasửdụng,Trongnước,68000,HàNội,Sốtựđộng,Xăng
...,...,...,...,...,...,...,...,...,...,...
1776,Hyundai Grand Starex 2.4 MT 2009,2.500000e+08,2009,Van/Minivan,Đãquasửdụng,Nhậpkhẩu,100000,HàNội,Sốtay,Xăng
1777,Hyundai Santa Fe SLX 2010,4.600000e+08,2010,SUV,Đãquasửdụng,Nhậpkhẩu,150000,Tp.HCM,Sốtựđộng,Xăng
1778,Toyota Camry 2.5Q 2013,6.500000e+08,2013,Sedan,Đãquasửdụng,Trongnước,8600,HàNội,Sốtựđộng,Xăng
1786,Toyota Yaris 1.3G 2014,3.800000e+08,2014,Hatchback,Đãquasửdụng,Nhậpkhẩu,92000,Tp.HCM,Sốtựđộng,Xăng
1787,Toyota Camry 1993,1.270000e+08,1993,Sedan,Đãquasửdụng,Nhậpkhẩu,68000,Tp.HCM,Sốtựđộng,Xăng